
export const Users = [
    {
        id: 1,
        avatar: 'https://images.unsplash.com/photo-1599032909756-5deb82fea3b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhdXR5JTIwZ2lybHxlbnwwfHwwfHw%3D&w=1000&q=80',
        name: 'User1  ffffffffffffffffffggggggg',
        contact: '@User1',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 2,
        avatar: 'https://i.pinimg.com/564x/4d/25/73/4d2573613020f2d11b0f662a55a2c3a0.jpg',
        name: 'User2',
        contact: '@User2',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 3,
        avatar: 'https://assets.architecturaldigest.in/photos/600822c71363405bf8eb4ebd/master/w_1600%2Cc_limit/Lionel-Messi-FIFA-Player-of-the-Year-2.jpg',
        name: 'User3',
        contact: '@User3',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 4,
        avatar: 'https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=425,format=auto/sites/default/files/styles/768x768/public/d8/images/methode/2020/06/24/cf9d675c-b1fe-11ea-953d-a7ecc5cbd229_image_hires_144326.jpg?itok=cjfUeF1R&v=1592981014',
        name: 'User4',
        contact: '@User4',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 5,
        avatar: 'https://qph.fs.quoracdn.net/main-qimg-5a6efb9f21fd4ebe2e4417c9f4658e40-lq',
        name: 'User5',
        contact: '@User5',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 6,
        avatar: 'https://static1.straitstimes.com.sg/s3fs-public/articles/2019/11/13/nz_sakura_131158.jpg?VersionId=WkxXfCaedt4ecUsY_MHtCe1e7rG.OW6k',
        name: 'User6',
        contact: '@User6',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 7,
        avatar: 'https://wallpapercave.com/wp/wp7049488.jpg',
        name: 'User7',
        contact: '@User7',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 8,
        avatar: 'https://www.planetsport.com/image-library/square/500/k/kylian-mbappe-psg-profile-january-2021.jpg',
        name: 'User8',
        contact: '@User8',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 9,
        avatar: 'https://ragus.vn/wp-content/uploads/2019/11/dien-vien-nhat-ban-Kanna-Hashimoto.jpg',
        name: 'User9',
        contact: '@User9',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
    {
        id: 10,
        avatar: 'https://file.tinnhac.com/resize/600x-/music/2017/09/13/images814767taylorsw-c29a.jpg',
        name: 'User10',
        contact: '@User10',
        location: "San Francisco, CA",
        description: "The Real Twitter API. Tweets about API changes, service issues and our Developer Platform. Don't get an answer? It's on my website.",
        isFollow: false,
    },
]